# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

#unset MODULEPATH

source /semifive/tools/Modules/default/init/bash
source /semifive/tools/Modules/default/init/bash_completion

